Repository fin-special/chicken_price_prediction, pull requests merged in 2022-11, with the labels that each got.

#63 불용어 처리 중간과정
  데이터전처리/sseung.ipynb
  데이터전처리/sseung.py
  크롤링/네이버뉴스.py
Labels: enhancement

#58 상관관계 히트맵 그림
  데이터시각화/hyebin.ipynb
  데이터시각화/jungki.ipynb
  데이터시각화/visualization.ipynb
  데이터전처리/hyebin.ipynb
Labels: enhancement, chore

#69 불용어처리 완료1102
  데이터전처리/sseung.py
Labels: enhancement

#71 modeling 진행 중 중간 push
  데이터시각화/hyebin.ipynb
  데이터시각화/warnings.log
  데이터전처리/hyebin.ipynb
Labels: enhancement, feature

#74 Sseung
  데이터전처리/sseung.py
Labels: chore

#76 feat: 데이터정규화 완료
  데이터전처리/데이터정규화/breeding.ipynb
  데이터전처리/데이터정규화/chickPrice.ipynb
  데이터전처리/데이터정규화/feedprice.ipynb
  데이터전처리/데이터정규화/income.ipynb
  데이터전처리/데이터정규화/killed.ipynb
  데이터전처리/데이터정규화/oilPrice.ipynb
Labels: feature

#78 LDA(토픽 모델링) 모델링 초안
  데이터시각화/hyebin.ipynb
  데이터시각화/topic_modeling.ipynb
Labels: enhancement, feature

#80 토픽모델링 완료
  모델링/ldaModel.html
  모델링/modelingPractice.ipynb
Labels: feature

#85 LSTM, Prophet 코드 추가
  데이터시각화/hyebin.ipynb
  데이터시각화/k.cps
  데이터시각화/model/tmp_checkpoint.h5
  데이터시각화/topic_modeling.ipynb
Labels: enhancement

#86 지승이가 random forest 맡아주세요~!
  데이터시각화/hyebin.ipynb
  데이터시각화/model/tmp_checkpoint.h5
  데이터전처리/hyebin.ipynb
Labels: help wanted

#92 git 정리 필요
  DB에서 Prophet 실행/Prophet_돼지고기가격.ipynb
  DB에서 Prophet 실행/Prophet_돼지고기가격_실시간예측.py
  DB에서 Prophet 실행/Prophet_소고기가격.ipynb
  DB에서 Prophet 실행/Prophet_소고기가격_실시간예측.py
  DB에서 Prophet 실행/Prophet_호수별_닭고기가격_실시간학습_최종.ipynb
  DB에서 Prophet 실행/Prophet_호수별_닭고기가격_실시간학습_최종.py
  data/readme.md
  practice.ipynb
  pre_data/readme.md
  가격 크롤링 DB 저장/chicken_week_crawling.py
  가격 크롤링 DB 저장/cow_week_crawling.py
  가격 크롤링 DB 저장/pork_week_crawling.py
  가격 크롤링 DB 저장/돼지고기가격_전처리.ipynb
  가격 크롤링 DB 저장/소고기가격_전처리.ipynb
  그래프 그리기용 Prophet/Prophet_돼지고기가격 그래프용.ipynb
  그래프 그리기용 Prophet/그래프용_닭고기.py
  그래프 그리기용 Prophet/그래프용_돼지고기.py
  그래프 그리기용 Prophet/그래프용_소고기.py
  기사 크롤링 DB 저장/new_크롤링_def.py
  기사 크롤링 DB 저장/news_chicken.py
  기사 크롤링 DB 저장/news_cow.py
  기사 크롤링 DB 저장/news_pork.ipynb
  기사 크롤링 DB 저장/news_pork.py
  데이터시각화/hyebin.ipynb
  데이터시각화/model/tmp_checkpoint.h5
  데이터전처리/hyebin.ipynb
  모델링/hyebin.ipynb
  모델링/hyebin_new_model.ipynb
  모델링/ldaModel.html
  모델링/lstm3.ipynb
  모델링/topic_modeling.ipynb
Labels: chore
