Repository fin-special/chicken_price_prediction, pull requests merged in 2022-10, with the labels that each got.

#4 21년데이터 및 전처리 일부
  데이터처리/닭고기데이터/2021전국기온_수정.csv
  데이터처리/닭고기데이터/~$축산농가_질병발생_통계.xlsx
  데이터처리/닭고기데이터/국제_원유가격_2021년.csv
  데이터처리/닭고기데이터/닭고기시세20120101_20211231.csv
  데이터처리/닭고기데이터/닭고기시세20210101_20211231.csv
  데이터처리/닭고기데이터/축산농가_질병발생_통계.xlsx
  데이터처리/데이터보기.ipynb
Labels: enhancement

#20 깃허브 정리
  .gitignore
  2012-2021 기온 daily.csv
  2012-2021기온.csv
  drop_duplicates_first.csv
  montly_chicken_price.csv
  preprocessing.ipynb
  temperature.ipynb
  네이버뉴스.ipynb
  데이터처리/temperature.ipynb
  데이터처리/닭고기데이터/2021전국기온_수정.csv
  데이터처리/닭고기데이터/~$축산농가_질병발생_통계.xlsx
  데이터처리/닭고기데이터/국제_원유가격_2021년.csv
  데이터처리/닭고기데이터/닭고기시세20120101_20211231.csv
  데이터처리/닭고기데이터/닭고기시세20210101_20211231.csv
  데이터처리/닭고기데이터/축산농가_질병발생_통계.xlsx
  데이터처리/데이터보기.ipynb
  크롤링/2021년1분기url.csv
  크롤링/2021년1분기뉴스.csv
  크롤링/2021년2분기url.csv
  크롤링/2021년2분기뉴스.csv
  크롤링/2021년3분기url.csv
  크롤링/2021년3분기뉴스.csv
  크롤링/2021년4분기url.csv
  크롤링/2021년4분기뉴스.csv
Labels: documentation

#24 데이터셋 담을폴더 생성
  데이터전처리/data/readme.md
  데이터전처리/jungki.ipynb
  데이터전처리/pre_data/readme.md
  데이터전처리/temperature.ipynb
  데이터전처리/데이터보기.ipynb
  크롤링/네이버뉴스.py
Labels: feature

#25 Hyebin 전처리 완료
  데이터처리/hyebin.ipynb
Labels: enhancement

#27 feat: 데이터전처리수행
  데이터전처리/jungki.ipynb
Labels: feature

#28 Yubin
  데이터처리/yubin.ipynb
Labels: feature

#30 폴더 병합
  데이터전처리/hyebin.ipynb
  데이터전처리/yubin.ipynb
Labels: etc

#34 네이버뉴스 크롤링코드튜닝만
  크롤링/네이버뉴스.py
Labels: enhancement

#36 데이터 통합/상관관계 확인
  데이터시각화/visualization.ipynb
  데이터전처리/hyebin.ipynb
  데이터전처리/jungki.ipynb
  데이터전처리/yubin.ipynb
Labels: documentation, enhancement

#38 월별 데이터 그래프
  데이터시각화/yubin.ipynb
Labels: documentation

#41 월초에서 월말로 변환
  데이터전처리/hyebin.ipynb
Labels: documentation

#43 분기 데이터 확인
  데이터전처리/hyebin.ipynb
Labels: documentation

#45 닭고기가격에 영향을 미치는 여러변수의 상관관계 분석을 위한 데이터시각화
  4.2.0
  데이터시각화/jungki.ipynb
  데이터전처리/hyebin.ipynb
  데이터전처리/jungki.ipynb
  데이터전처리/yubin.ipynb
  데이터전처리/데이터보기.ipynb
Labels: feature

#52 add gitignore
  .gitignore
Labels: documentation

#53 크롤링데이터 주요단어 빈도분석
  데이터전처리/sseung.ipynb
  데이터전처리/sseung.py
Labels: feature

#54 Delete 4.2.0
  4.2.0
Labels: chore

#55 minor update for crawl code
  데이터전처리/word_extract.ipynb
  크롤링/네이버뉴스.py
Labels: enhancement
